# Directory Structure
paths:
  base:
    inbox: Notes.md
    tasks: Tasks
    journal: Journals
    lists: Lists
    people: People
    archives: Knowledge Archive

  subdirs:
    tasks:
      completed: Completed

    journal:
      completed: Journals/completed

# User Journals
journals:
  - name: Belle
  - name: Pure

# System Settings
settings:
  retention:
    empty_task: 30
    project_before_archive: 7

  patterns:
    date_format: "YYYY-MM-DD"
    file_format: "*-YYYY-MM-DD"
